name: Create landing zone file

run-name: Create landing zone for ${{ inputs.accountName }} - ${{ inputs.accountEmail }}

on:
  workflow_dispatch:
    inputs:
      accountEmail:
        required: true
        description: "New account email"
        type: string
      accountName:
        required: true
        description: "New account name"
        type: string
      ssoUserFirstName:
        required: true
        description: "New account SSO user first name"
        type: string
      ssoUserLastName:
        required: true
        description: "New account SSO user last name"
        type: string
      port_payload:
        required: true
        description: "Port's payload, including details for who triggered the action and general context (blueprint, run id, etc...)"
        type: string

jobs:
  create-landing-zone-file:
    name: Create new landing zone file from inputs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Call script to generate new file
        run: |
          python .github/scripts/create_landing_zone_file.py ${{ github.event.inputs.accountEmail }} ${{ github.event.inputs.accountName }} ${{ github.event.inputs.ssoUserFirstName }} ${{ github.event.inputs.ssoUserLastName }}
      - name: Commit new landing zone file
        run: |
          git config --global user.email "devops@orca.security"
          git config --global user.name "Devops automated GitHub action for port"
          git add .
          git commit -m "${{fromJson(github.event.inputs.port_payload).context.runId}} add new landing zone for account ${{ github.event.inputs.accountName }}"
          git push --force-with-lease origin main
      - name: "Report deployment Entity to port 🚢"
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          identifier: ${{ github.event.inputs.accountName }}
          blueprint: landingZone
          title: ${{ github.event.inputs.accountName }}
          properties: |
            {
               "email": "${{ github.event.inputs.accountEmail }}",
               "ssoUserFirstName": "${{ github.event.inputs.ssoUserFirstName }}",
               "ssoUserLastName": "${{ github.event.inputs.ssoUserLastName }}",
               "status": "Provisioning"
            }
          runId: "${{fromJson(github.event.inputs.port_payload).context.runId}}"

  report-deployment:
   name: Update deployment Entity
   needs: create-landing-zone-file
   runs-on: ubuntu-latest
   steps:
     - name: Extract SHA short
       run: echo "SHA_SHORT=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
     - name: "Report deployment Entity to port 🚢"
       uses: port-labs/port-github-action@v1
       with:
         clientId: ${{ secrets.PORT_CLIENT_ID }}
         clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
         identifier: ${{ github.event.inputs.accountName }}
         blueprint: landingZone
         title: ${{ github.event.inputs.accountName }}
         properties: |
           {
              "email": "${{ github.event.inputs.accountEmail }}",
              "ssoUserFirstName": "${{ github.event.inputs.ssoUserFirstName }}",
              "ssoUserLastName": "${{ github.event.inputs.ssoUserLastName }}",
              "status": "Active"
           }
         runId: "${{fromJson(github.event.inputs.port_payload).context.runId}}"